### ISSUE TITLE
Incorrect behavior when interacting with filtered list

### ISSUE THREAD

**Issue by bmathews** [WebReflection/hypermvc#1]
When the list is filtered, deleting or completing todo items works incorrectly.

The index stored on the dom is the array index of the filtered list
https://github.com/WebReflection/hypermvc/blob/master/js/views/main.js#L14

Then controller actions use that filtered array index incorrectly, on the unfiltered array:
https://github.com/WebReflection/hypermvc/blob/master/js/controllers/todo.js#L40

**Comment by WebReflection** [comment]
Are you sure? 'cause all official tests pass.

Can you please give me a sequence of actions that shows the issue?

**Comment by bmathews** [comment]
Add two items. 'Complete' the last item. Filter to completed. Try to remove. The wrong item gets removed (index 0 of unfiltered list)

![kapture 2017-03-22 at 8 49 34](https://cloud.githubusercontent.com/assets/848347/24206761/7f03ddbc-0edc-11e7-8a1e-22a84158847f.gif)

**Comment by WebReflection** [comment]
it should always work as expected now, thanks.
